### ISSUE TITLE
Python version < 3.10 does not support None as type hint

### ISSUE THREAD

**Issue by achaosss** [lernanto/sincomp#34]
>>> import sincomp.datasets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Z19070948\Desktop\python39\lib\site-packages\sincomp\datasets.py", line 29, in <module>
    from . import preprocess
  File "C:\Users\Z19070948\Desktop\python39\lib\site-packages\sincomp\preprocess.py", line 673, in <module>
    values: list[str] | None = None,
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

**Comment by lernanto** [comment]
Python 版本太低了，不支持 None 作为 type hint。需要 Python >= 3.10。
